export const siteTitle = "TL;DR Crypto"
export const siteSubTitle = "Join thousands of others and never miss out on new tips, tutorials, and more."
export const siteDescription = "Lorem Ipsum"
export const siteUrl = "https://www.tldr-crypto.com"
export const siteLogo = "/logo.png"
export const siteLogoLight = "/logo-light-250x250.png"
export const siteLogoDark = "/logo-dark-250x250.png"
export const webmasterEmail = "support@tldr-crypto.com"

export const instagramProfile = "https://www.reddit.com/user/tldr_crypto"
export const tiktokProfile = "https://www.reddit.com/user/tldr_crypto"
export const telegramProfile = "https://t.me/crypto_news_broadcast"
export const redditProfile = "https://www.reddit.com/user/tldr_crypto"
export const youtubeProfile = "https://www.youtube.com/channel/UCtbXygpOlvdmj42uVTrXn_g"
export const twitterProfile = "https://twitter.com/tl_drCrypto"
export const twitterHandle = "tl_drCrypto"

export const authorName = "Constantin"
export const authorDescription = "Lorem Ipsum"
export const authorProfileImageSrc = "/images/authors/constantin_thumbs_up.png"